import { Geist, Geist_Mono } from "next/font/google";
import Header from '@/components/header';
import Footer from '@/components/footer';
import CookieConsent from '@/components/cookieConsent';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen flex flex-col">
          <Header />

          <main className="flex-1">
            <div className="max-w-7xl mx-auto px-6">
              {children}
            </div>
          </main>

          <Footer />
          <CookieConsent />
        </div>
      </body>
    </html>
  );
}
